path_7b: /home/pubw/proj/Qwen2-VL-7B-Instruct
path_2b: /home/pubw/proj/Qwen2-VL-2B-Instruct
json_path: /home/pubw/datasets/www25/train/train_task1.json
image_path: /home/pubw/datasets/www25/train/images/
save_path: save
id: cot_train_task1
model: cot
